# Generated by Django 5.2.2 on 2025-08-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a profile image (JPG, PNG, WebP)', null=True, upload_to='profile_images/'),
        ),
    ]
