[build]
  publish = "dist"
  command = "npm run build"
  
[build.processing]
  skip_processing = false
  
[build.processing.css]
  bundle = true
  minify = true
  
[build.processing.js]
  bundle = true
  minify = true
  
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_BASE_URL = "https://wrytera.netlify.app"
  NODE_ENV = "production"

[context.deploy-preview.environment]
  VITE_API_BASE_URL = "https://wrytera.netlify.app"

[context.branch-deploy.environment]
  VITE_API_BASE_URL = "https://wrytera.netlify.app"
