[build]
  command = "pip install --upgrade pip && pip install -r requirements-netlify.txt"
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
