# Generated by Django 5.2.2 on 2025-08-05 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postview',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['post', 'user'], name='post_views_post_id_22f1b6_idx'),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['post', 'ip_address'], name='post_views_post_id_dffebf_idx'),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['viewed_at'], name='post_views_viewed__7bf7ac_idx'),
        ),
    ]
