# Generated by Django 5.2.2 on 2025-08-06 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_postview_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allow_tips',
            field=models.BooleanField(default=True, help_text='Allow readers to tip the author'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Mark as premium/paid content'),
        ),
        migrations.AddField(
            model_name='post',
            name='premium_preview',
            field=models.TextField(blank=True, help_text='Preview text for premium content', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='premium_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for premium content', max_digits=10),
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField(blank=True, help_text='Optional message with the tip', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='posts.post')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips_received', to=settings.AUTH_USER_MODEL)),
                ('tipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('daily_words', 'Daily Word Count'), ('weekly_posts', 'Weekly Posts'), ('monthly_revenue', 'Monthly Revenue'), ('follower_count', 'Follower Target')], max_length=20)),
                ('target_value', models.IntegerField(help_text='Target number to achieve')),
                ('current_value', models.IntegerField(default=0)),
                ('deadline', models.DateField()),
                ('is_achieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'writing_goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaborativePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('co_author', 'Co-Author'), ('editor', 'Editor'), ('reviewer', 'Reviewer')], default='co_author', max_length=20)),
                ('contribution_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Revenue share percentage', max_digits=5)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborative_posts', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='posts.post')),
            ],
            options={
                'db_table': 'collaborative_posts',
                'ordering': ['-invited_at'],
                'unique_together': {('post', 'collaborator')},
            },
        ),
        migrations.CreateModel(
            name='PremiumAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_purchases', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'premium_access',
                'ordering': ['-purchased_at'],
                'unique_together': {('user', 'post')},
            },
        ),
        migrations.CreateModel(
            name='ReaderMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('inspired', '✨ Inspired'), ('informed', '🧠 Informed'), ('entertained', '😄 Entertained'), ('moved', '❤️ Emotionally Moved'), ('motivated', '💪 Motivated'), ('thoughtful', '🤔 Made Me Think'), ('happy', '😊 Happy'), ('surprised', '😲 Surprised')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader_moods', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reader_moods',
                'ordering': ['-created_at'],
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='monthly', max_length=20)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_subscriptions',
                'ordering': ['-started_at'],
                'unique_together': {('subscriber', 'author')},
            },
        ),
    ]
