# Generated by Django 5.2.2 on 2025-08-08 15:37

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_collaborative_filtering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumaccess',
            name='post',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='premium_access_entries',
                to='posts.post'
            ),
        ),
        migrations.AlterField(
            model_name='premiumaccess',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='premium_access_entries',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
