# Generated by Django 5.2.2 on 2025-08-09 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_fix_premium_access_related_names'),
    ]

    operations = [
    ]
